/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.4.1
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.api;

import io.flexify.apiclient.handler.ApiException;
import io.flexify.apiclient.model.BillingAccountWithMoney;
import io.flexify.apiclient.model.CostDetails;
import io.flexify.apiclient.model.Payment;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BillingAccountControllerApi
 */
@Ignore
public class BillingAccountControllerApiTest {

    private final BillingAccountControllerApi api = new BillingAccountControllerApi();

    
    /**
     * Get costs for current user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCostsForCurrentUserTest() throws ApiException {
        List<CostDetails> response = api.getCostsForCurrentUser();

        // TODO: test validations
    }
    
    /**
     * Get billing account for current user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCurrentUserBillingAccountTest() throws ApiException {
        BillingAccountWithMoney response = api.getCurrentUserBillingAccount();

        // TODO: test validations
    }
    
    /**
     * Get payments for current user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentsForCurrentUserTest() throws ApiException {
        List<Payment> response = api.getPaymentsForCurrentUser();

        // TODO: test validations
    }
    
}
