/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.4.0
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.api;

import io.flexify.apiclient.handler.ApiException;
import io.flexify.apiclient.model.DbLogEntry;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogControllerApi
 */
@Ignore
public class LogControllerApiTest {

    private final LogControllerApi api = new LogControllerApi();

    
    /**
     * getLogForCurrentUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLogForCurrentUserUsingGETTest() throws ApiException {
        Long storageId = null;
        Long migrationId = null;
        Long endpointId = null;
        List<DbLogEntry> response = api.getLogForCurrentUserUsingGET(storageId, migrationId, endpointId);

        // TODO: test validations
    }
    
}
