/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.8.5
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.api;

import io.flexify.apiclient.handler.ApiException;
import io.flexify.apiclient.model.RequestResetPasswordRequest;
import io.flexify.apiclient.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersControllerApi
 */
@Ignore
public class UsersControllerApiTest {

    private final UsersControllerApi api = new UsersControllerApi();

    
    /**
     * Get details of user correponsing to provided auth token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCurrentUserTest() throws ApiException {
        String contextPath = null;
        String localeISO3Country = null;
        String localeISO3Language = null;
        String localeCountry = null;
        String localeDisplayCountry = null;
        String localeDisplayLanguage = null;
        String localeDisplayName = null;
        String localeDisplayScript = null;
        String localeDisplayVariant = null;
        String localeLanguage = null;
        String localeScript = null;
        List<String> localeUnicodeLocaleAttributes = null;
        List<String> localeUnicodeLocaleKeys = null;
        String localeVariant = null;
        String remoteUser = null;
        Boolean secure = null;
        String userPrincipalName = null;
        User response = api.getCurrentUser(contextPath, localeISO3Country, localeISO3Language, localeCountry, localeDisplayCountry, localeDisplayLanguage, localeDisplayName, localeDisplayScript, localeDisplayVariant, localeLanguage, localeScript, localeUnicodeLocaleAttributes, localeUnicodeLocaleKeys, localeVariant, remoteUser, secure, userPrincipalName);

        // TODO: test validations
    }
    
    /**
     * requestDelete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestDeleteTest() throws ApiException {
        api.requestDelete();

        // TODO: test validations
    }
    
    /**
     * requestResetPassword
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestResetPasswordTest() throws ApiException {
        RequestResetPasswordRequest request = null;
        api.requestResetPassword(request);

        // TODO: test validations
    }
    
}
