/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.4.1
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.flexify.apiclient.model.Bucket;
import io.flexify.apiclient.model.StorageAccountCreateRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * AddStorageAccountRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-18T17:03:35.898+03:00")
public class AddStorageAccountRequest {
  @JsonProperty("storageAccount")
  private StorageAccountCreateRequest storageAccount = null;

  @JsonProperty("buckets")
  private List<Bucket> buckets = null;

  @JsonProperty("endpointId")
  private Long endpointId = null;

  public AddStorageAccountRequest storageAccount(StorageAccountCreateRequest storageAccount) {
    this.storageAccount = storageAccount;
    return this;
  }

   /**
   * Storage account to create
   * @return storageAccount
  **/
  @ApiModelProperty(value = "Storage account to create")
  public StorageAccountCreateRequest getStorageAccount() {
    return storageAccount;
  }

  public void setStorageAccount(StorageAccountCreateRequest storageAccount) {
    this.storageAccount = storageAccount;
  }

  public AddStorageAccountRequest buckets(List<Bucket> buckets) {
    this.buckets = buckets;
    return this;
  }

  public AddStorageAccountRequest addBucketsItem(Bucket bucketsItem) {
    if (this.buckets == null) {
      this.buckets = new ArrayList<Bucket>();
    }
    this.buckets.add(bucketsItem);
    return this;
  }

   /**
   * Lists of buckets
   * @return buckets
  **/
  @ApiModelProperty(value = "Lists of buckets")
  public List<Bucket> getBuckets() {
    return buckets;
  }

  public void setBuckets(List<Bucket> buckets) {
    this.buckets = buckets;
  }

  public AddStorageAccountRequest endpointId(Long endpointId) {
    this.endpointId = endpointId;
    return this;
  }

   /**
   * ID of the user endpoint to add storages to. Do not set the value if you want to attach storages to the endpoint later
   * @return endpointId
  **/
  @ApiModelProperty(value = "ID of the user endpoint to add storages to. Do not set the value if you want to attach storages to the endpoint later")
  public Long getEndpointId() {
    return endpointId;
  }

  public void setEndpointId(Long endpointId) {
    this.endpointId = endpointId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddStorageAccountRequest addStorageAccountRequest = (AddStorageAccountRequest) o;
    return Objects.equals(this.storageAccount, addStorageAccountRequest.storageAccount) &&
        Objects.equals(this.buckets, addStorageAccountRequest.buckets) &&
        Objects.equals(this.endpointId, addStorageAccountRequest.endpointId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storageAccount, buckets, endpointId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddStorageAccountRequest {\n");
    
    sb.append("    storageAccount: ").append(toIndentedString(storageAccount)).append("\n");
    sb.append("    buckets: ").append(toIndentedString(buckets)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

