/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.4.0
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.flexify.apiclient.model.DbLogEvent;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DbLogEntry
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-07T17:03:52.903+03:00")
public class DbLogEntry {
  @JsonProperty("endpointId")
  private Long endpointId = null;

  @JsonProperty("engineUuid")
  private String engineUuid = null;

  @JsonProperty("event")
  private DbLogEvent event = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("migrationId")
  private Long migrationId = null;

  @JsonProperty("storgaeId")
  private Long storgaeId = null;

  @JsonProperty("taskUuid")
  private String taskUuid = null;

  public DbLogEntry endpointId(Long endpointId) {
    this.endpointId = endpointId;
    return this;
  }

   /**
   * Get endpointId
   * @return endpointId
  **/
  @ApiModelProperty(value = "")
  public Long getEndpointId() {
    return endpointId;
  }

  public void setEndpointId(Long endpointId) {
    this.endpointId = endpointId;
  }

  public DbLogEntry engineUuid(String engineUuid) {
    this.engineUuid = engineUuid;
    return this;
  }

   /**
   * Get engineUuid
   * @return engineUuid
  **/
  @ApiModelProperty(value = "")
  public String getEngineUuid() {
    return engineUuid;
  }

  public void setEngineUuid(String engineUuid) {
    this.engineUuid = engineUuid;
  }

  public DbLogEntry event(DbLogEvent event) {
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  @ApiModelProperty(value = "")
  public DbLogEvent getEvent() {
    return event;
  }

  public void setEvent(DbLogEvent event) {
    this.event = event;
  }

  public DbLogEntry id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public DbLogEntry migrationId(Long migrationId) {
    this.migrationId = migrationId;
    return this;
  }

   /**
   * Get migrationId
   * @return migrationId
  **/
  @ApiModelProperty(value = "")
  public Long getMigrationId() {
    return migrationId;
  }

  public void setMigrationId(Long migrationId) {
    this.migrationId = migrationId;
  }

  public DbLogEntry storgaeId(Long storgaeId) {
    this.storgaeId = storgaeId;
    return this;
  }

   /**
   * Get storgaeId
   * @return storgaeId
  **/
  @ApiModelProperty(value = "")
  public Long getStorgaeId() {
    return storgaeId;
  }

  public void setStorgaeId(Long storgaeId) {
    this.storgaeId = storgaeId;
  }

  public DbLogEntry taskUuid(String taskUuid) {
    this.taskUuid = taskUuid;
    return this;
  }

   /**
   * Get taskUuid
   * @return taskUuid
  **/
  @ApiModelProperty(value = "")
  public String getTaskUuid() {
    return taskUuid;
  }

  public void setTaskUuid(String taskUuid) {
    this.taskUuid = taskUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DbLogEntry dbLogEntry = (DbLogEntry) o;
    return Objects.equals(this.endpointId, dbLogEntry.endpointId) &&
        Objects.equals(this.engineUuid, dbLogEntry.engineUuid) &&
        Objects.equals(this.event, dbLogEntry.event) &&
        Objects.equals(this.id, dbLogEntry.id) &&
        Objects.equals(this.migrationId, dbLogEntry.migrationId) &&
        Objects.equals(this.storgaeId, dbLogEntry.storgaeId) &&
        Objects.equals(this.taskUuid, dbLogEntry.taskUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointId, engineUuid, event, id, migrationId, storgaeId, taskUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DbLogEntry {\n");
    
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    engineUuid: ").append(toIndentedString(engineUuid)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    migrationId: ").append(toIndentedString(migrationId)).append("\n");
    sb.append("    storgaeId: ").append(toIndentedString(storgaeId)).append("\n");
    sb.append("    taskUuid: ").append(toIndentedString(taskUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

