/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.6
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * NewEndpointStorage
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-21T12:54:18.961+08:00")
public class NewEndpointStorage {
  @JsonProperty("putObjects")
  private Boolean putObjects = null;

  @JsonProperty("storageId")
  private Long storageId = null;

  public NewEndpointStorage putObjects(Boolean putObjects) {
    this.putObjects = putObjects;
    return this;
  }

   /**
   * Save new data to this storage
   * @return putObjects
  **/
  @ApiModelProperty(example = "false", value = "Save new data to this storage")
  public Boolean isPutObjects() {
    return putObjects;
  }

  public void setPutObjects(Boolean putObjects) {
    this.putObjects = putObjects;
  }

  public NewEndpointStorage storageId(Long storageId) {
    this.storageId = storageId;
    return this;
  }

   /**
   * ID of storage to be attached
   * @return storageId
  **/
  @ApiModelProperty(value = "ID of storage to be attached")
  public Long getStorageId() {
    return storageId;
  }

  public void setStorageId(Long storageId) {
    this.storageId = storageId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewEndpointStorage newEndpointStorage = (NewEndpointStorage) o;
    return Objects.equals(this.putObjects, newEndpointStorage.putObjects) &&
        Objects.equals(this.storageId, newEndpointStorage.storageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(putObjects, storageId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewEndpointStorage {\n");
    
    sb.append("    putObjects: ").append(toIndentedString(putObjects)).append("\n");
    sb.append("    storageId: ").append(toIndentedString(storageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

