/*
 * Flexify IO User REST API
 * + Get API token + Authorize using `Bearer TOKEN` + Enjoy Flexify IO REST API
 *
 * OpenAPI spec version: 2.14.0
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * OAuth2DeviceCodeResponse
 */

public class OAuth2DeviceCodeResponse {
  @JsonProperty("device_code")
  private String deviceCode = null;

  @JsonProperty("expires_in")
  private Long expiresIn = null;

  @JsonProperty("interval")
  private Long interval = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("user_code")
  private String userCode = null;

  @JsonProperty("verification_uri")
  private String verificationUri = null;

  public OAuth2DeviceCodeResponse deviceCode(String deviceCode) {
    this.deviceCode = deviceCode;
    return this;
  }

   /**
   * Get deviceCode
   * @return deviceCode
  **/
  @ApiModelProperty(value = "")
  public String getDeviceCode() {
    return deviceCode;
  }

  public void setDeviceCode(String deviceCode) {
    this.deviceCode = deviceCode;
  }

  public OAuth2DeviceCodeResponse expiresIn(Long expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

   /**
   * Get expiresIn
   * @return expiresIn
  **/
  @ApiModelProperty(value = "")
  public Long getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(Long expiresIn) {
    this.expiresIn = expiresIn;
  }

  public OAuth2DeviceCodeResponse interval(Long interval) {
    this.interval = interval;
    return this;
  }

   /**
   * Get interval
   * @return interval
  **/
  @ApiModelProperty(value = "")
  public Long getInterval() {
    return interval;
  }

  public void setInterval(Long interval) {
    this.interval = interval;
  }

  public OAuth2DeviceCodeResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public OAuth2DeviceCodeResponse userCode(String userCode) {
    this.userCode = userCode;
    return this;
  }

   /**
   * Get userCode
   * @return userCode
  **/
  @ApiModelProperty(value = "")
  public String getUserCode() {
    return userCode;
  }

  public void setUserCode(String userCode) {
    this.userCode = userCode;
  }

  public OAuth2DeviceCodeResponse verificationUri(String verificationUri) {
    this.verificationUri = verificationUri;
    return this;
  }

   /**
   * Get verificationUri
   * @return verificationUri
  **/
  @ApiModelProperty(value = "")
  public String getVerificationUri() {
    return verificationUri;
  }

  public void setVerificationUri(String verificationUri) {
    this.verificationUri = verificationUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OAuth2DeviceCodeResponse oauth2DeviceCodeResponse = (OAuth2DeviceCodeResponse) o;
    return Objects.equals(this.deviceCode, oauth2DeviceCodeResponse.deviceCode) &&
        Objects.equals(this.expiresIn, oauth2DeviceCodeResponse.expiresIn) &&
        Objects.equals(this.interval, oauth2DeviceCodeResponse.interval) &&
        Objects.equals(this.message, oauth2DeviceCodeResponse.message) &&
        Objects.equals(this.userCode, oauth2DeviceCodeResponse.userCode) &&
        Objects.equals(this.verificationUri, oauth2DeviceCodeResponse.verificationUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceCode, expiresIn, interval, message, userCode, verificationUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuth2DeviceCodeResponse {\n");
    
    sb.append("    deviceCode: ").append(toIndentedString(deviceCode)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    userCode: ").append(toIndentedString(userCode)).append("\n");
    sb.append("    verificationUri: ").append(toIndentedString(verificationUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

