/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.4.0-SNAPSHOT
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.flexify.apiclient.model.Money;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Price List Entry
 */
@ApiModel(description = "Price List Entry")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-13T12:27:12.882+03:00")
public class PriceListEntry {
  /**
   * Billable counter (such as traffic or storage volume)
   */
  public enum CounterEnum {
    TRAFFIC("TRAFFIC"),
    
    STORAGE_VOLUME("STORAGE_VOLUME");

    private String value;

    CounterEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CounterEnum fromValue(String text) {
      for (CounterEnum b : CounterEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("counter")
  private CounterEnum counter = null;

  @JsonProperty("price")
  private Money price = null;

  /**
   * Service
   */
  public enum ServiceEnum {
    MIGRATION("DATA_MIGRATION"),
    
    FORWARDING("DATA_FORWARDING");

    private String value;

    ServiceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ServiceEnum fromValue(String text) {
      for (ServiceEnum b : ServiceEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("service")
  private ServiceEnum service = null;

  @JsonProperty("unitName")
  private String unitName = null;

  @JsonProperty("unitSize")
  private Long unitSize = null;

  public PriceListEntry counter(CounterEnum counter) {
    this.counter = counter;
    return this;
  }

   /**
   * Billable counter (such as traffic or storage volume)
   * @return counter
  **/
  @ApiModelProperty(example = "TRAFFIC", value = "Billable counter (such as traffic or storage volume)")
  public CounterEnum getCounter() {
    return counter;
  }

  public void setCounter(CounterEnum counter) {
    this.counter = counter;
  }

  public PriceListEntry price(Money price) {
    this.price = price;
    return this;
  }

   /**
   * Price of one unit
   * @return price
  **/
  @ApiModelProperty(value = "Price of one unit")
  public Money getPrice() {
    return price;
  }

  public void setPrice(Money price) {
    this.price = price;
  }

  public PriceListEntry service(ServiceEnum service) {
    this.service = service;
    return this;
  }

   /**
   * Service
   * @return service
  **/
  @ApiModelProperty(example = "DATA_MIGRATION", value = "Service")
  public ServiceEnum getService() {
    return service;
  }

  public void setService(ServiceEnum service) {
    this.service = service;
  }

  public PriceListEntry unitName(String unitName) {
    this.unitName = unitName;
    return this;
  }

   /**
   * Name of billable unit
   * @return unitName
  **/
  @ApiModelProperty(example = "GB", value = "Name of billable unit")
  public String getUnitName() {
    return unitName;
  }

  public void setUnitName(String unitName) {
    this.unitName = unitName;
  }

  public PriceListEntry unitSize(Long unitSize) {
    this.unitSize = unitSize;
    return this;
  }

   /**
   * Size of billable unit in bytes
   * @return unitSize
  **/
  @ApiModelProperty(example = "1073741824", value = "Size of billable unit in bytes")
  public Long getUnitSize() {
    return unitSize;
  }

  public void setUnitSize(Long unitSize) {
    this.unitSize = unitSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceListEntry priceListEntry = (PriceListEntry) o;
    return Objects.equals(this.counter, priceListEntry.counter) &&
        Objects.equals(this.price, priceListEntry.price) &&
        Objects.equals(this.service, priceListEntry.service) &&
        Objects.equals(this.unitName, priceListEntry.unitName) &&
        Objects.equals(this.unitSize, priceListEntry.unitSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(counter, price, service, unitName, unitSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceListEntry {\n");
    
    sb.append("    counter: ").append(toIndentedString(counter)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    unitName: ").append(toIndentedString(unitName)).append("\n");
    sb.append("    unitSize: ").append(toIndentedString(unitSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

