/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.4.0
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.flexify.apiclient.model.DataStorageStat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Data Storage
 */
@ApiModel(description = "Data Storage")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-07T17:03:52.903+03:00")
public class Storage {
  @JsonProperty("bucket")
  private String bucket = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("stat")
  private DataStorageStat stat = null;

  public Storage bucket(String bucket) {
    this.bucket = bucket;
    return this;
  }

   /**
   * Bucket name
   * @return bucket
  **/
  @ApiModelProperty(example = "bucket-1", required = true, value = "Bucket name")
  public String getBucket() {
    return bucket;
  }

  public void setBucket(String bucket) {
    this.bucket = bucket;
  }

   /**
   * Unique identifier
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier")
  public Long getId() {
    return id;
  }

  public Storage stat(DataStorageStat stat) {
    this.stat = stat;
    return this;
  }

   /**
   * Storage statistics
   * @return stat
  **/
  @ApiModelProperty(value = "Storage statistics")
  public DataStorageStat getStat() {
    return stat;
  }

  public void setStat(DataStorageStat stat) {
    this.stat = stat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Storage storage = (Storage) o;
    return Objects.equals(this.bucket, storage.bucket) &&
        Objects.equals(this.id, storage.id) &&
        Objects.equals(this.stat, storage.stat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bucket, id, stat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Storage {\n");
    
    sb.append("    bucket: ").append(toIndentedString(bucket)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    stat: ").append(toIndentedString(stat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

