/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.7-SNAPSHOT
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Storage Provider
 */
@ApiModel(description = "Storage Provider")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-19T00:30:02.233+08:00")
public class StorageProvider {
  @JsonProperty("disabledAsDestination")
  private Boolean disabledAsDestination = null;

  @JsonProperty("endpoint")
  private String endpoint = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("portHttp")
  private Integer portHttp = null;

  @JsonProperty("portHttps")
  private Integer portHttps = null;

  @JsonProperty("productName")
  private String productName = null;

  /**
   * Storage protocol this provider uses
   */
  public enum ProtocolEnum {
    S3("S3"),
    
    AZURE("AZURE"),
    
    GOOGLE("GOOGLE"),
    
    OPENSTACK("OPENSTACK"),
    
    RACKSPACE("RACKSPACE");

    private String value;

    ProtocolEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProtocolEnum fromValue(String text) {
      for (ProtocolEnum b : ProtocolEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("protocol")
  private ProtocolEnum protocol = null;

  @JsonProperty("supportsHttp")
  private Boolean supportsHttp = null;

  @JsonProperty("supportsHttps")
  private Boolean supportsHttps = null;

  public StorageProvider disabledAsDestination(Boolean disabledAsDestination) {
    this.disabledAsDestination = disabledAsDestination;
    return this;
  }

   /**
   * Storage is not allowed to be used as a default storage in endpoint or as a migration destination)
   * @return disabledAsDestination
  **/
  @ApiModelProperty(example = "false", value = "Storage is not allowed to be used as a default storage in endpoint or as a migration destination)")
  public Boolean isDisabledAsDestination() {
    return disabledAsDestination;
  }

  public void setDisabledAsDestination(Boolean disabledAsDestination) {
    this.disabledAsDestination = disabledAsDestination;
  }

  public StorageProvider endpoint(String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Endpoint to access this provider or null for custom providers
   * @return endpoint
  **/
  @ApiModelProperty(example = "s3.amazonaws.com", value = "Endpoint to access this provider or null for custom providers")
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  public StorageProvider id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Id of the provider in the system
   * @return id
  **/
  @ApiModelProperty(value = "Id of the provider in the system")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public StorageProvider name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the provider
   * @return name
  **/
  @ApiModelProperty(example = "Amazon S3", value = "Name of the provider")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public StorageProvider portHttp(Integer portHttp) {
    this.portHttp = portHttp;
    return this;
  }

   /**
   * Port for HTTP request (null for default 80)
   * @return portHttp
  **/
  @ApiModelProperty(value = "Port for HTTP request (null for default 80)")
  public Integer getPortHttp() {
    return portHttp;
  }

  public void setPortHttp(Integer portHttp) {
    this.portHttp = portHttp;
  }

  public StorageProvider portHttps(Integer portHttps) {
    this.portHttps = portHttps;
    return this;
  }

   /**
   * Port for HTTPS request (null for default 443)
   * @return portHttps
  **/
  @ApiModelProperty(value = "Port for HTTPS request (null for default 443)")
  public Integer getPortHttps() {
    return portHttps;
  }

  public void setPortHttps(Integer portHttps) {
    this.portHttps = portHttps;
  }

  public StorageProvider productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * Name of product/region for this provider
   * @return productName
  **/
  @ApiModelProperty(example = "Blob Storage", value = "Name of product/region for this provider")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public StorageProvider protocol(ProtocolEnum protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Storage protocol this provider uses
   * @return protocol
  **/
  @ApiModelProperty(example = "S3", value = "Storage protocol this provider uses")
  public ProtocolEnum getProtocol() {
    return protocol;
  }

  public void setProtocol(ProtocolEnum protocol) {
    this.protocol = protocol;
  }

  public StorageProvider supportsHttp(Boolean supportsHttp) {
    this.supportsHttp = supportsHttp;
    return this;
  }

   /**
   * Indicates that HTTP is supported
   * @return supportsHttp
  **/
  @ApiModelProperty(example = "true", value = "Indicates that HTTP is supported")
  public Boolean isSupportsHttp() {
    return supportsHttp;
  }

  public void setSupportsHttp(Boolean supportsHttp) {
    this.supportsHttp = supportsHttp;
  }

  public StorageProvider supportsHttps(Boolean supportsHttps) {
    this.supportsHttps = supportsHttps;
    return this;
  }

   /**
   * Indicates that HTTPS (SSL) is supported
   * @return supportsHttps
  **/
  @ApiModelProperty(example = "true", value = "Indicates that HTTPS (SSL) is supported")
  public Boolean isSupportsHttps() {
    return supportsHttps;
  }

  public void setSupportsHttps(Boolean supportsHttps) {
    this.supportsHttps = supportsHttps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StorageProvider storageProvider = (StorageProvider) o;
    return Objects.equals(this.disabledAsDestination, storageProvider.disabledAsDestination) &&
        Objects.equals(this.endpoint, storageProvider.endpoint) &&
        Objects.equals(this.id, storageProvider.id) &&
        Objects.equals(this.name, storageProvider.name) &&
        Objects.equals(this.portHttp, storageProvider.portHttp) &&
        Objects.equals(this.portHttps, storageProvider.portHttps) &&
        Objects.equals(this.productName, storageProvider.productName) &&
        Objects.equals(this.protocol, storageProvider.protocol) &&
        Objects.equals(this.supportsHttp, storageProvider.supportsHttp) &&
        Objects.equals(this.supportsHttps, storageProvider.supportsHttps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disabledAsDestination, endpoint, id, name, portHttp, portHttps, productName, protocol, supportsHttp, supportsHttps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StorageProvider {\n");
    
    sb.append("    disabledAsDestination: ").append(toIndentedString(disabledAsDestination)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    portHttp: ").append(toIndentedString(portHttp)).append("\n");
    sb.append("    portHttps: ").append(toIndentedString(portHttps)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    supportsHttp: ").append(toIndentedString(supportsHttp)).append("\n");
    sb.append("    supportsHttps: ").append(toIndentedString(supportsHttps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

