/*
 * Flexify.IO User REST API
 * + Generate access token via `/rest/auth` + Authorize in Swagger UI using `Bearer TOKEN` + Enjoy Flexify.IO REST API
 *
 * OpenAPI spec version: 2.4.1
 * Contact: info@flexify.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.flexify.apiclient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.flexify.apiclient.model.BillingAccount;
import io.flexify.apiclient.model.DescribeOrganization;
import io.flexify.apiclient.model.UserProfile;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * User
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-18T17:03:35.898+03:00")
public class User {
  @JsonProperty("account")
  private BillingAccount account = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("org")
  private DescribeOrganization org = null;

  @JsonProperty("profile")
  private UserProfile profile = null;

  @JsonProperty("registered")
  private DateTime registered = null;

  @JsonProperty("resourceLastModified")
  private Long resourceLastModified = null;

  /**
   * Gets or Sets roles
   */
  public enum RolesEnum {
    USER("ROLE_USER"),
    
    ADMIN("ROLE_ADMIN"),
    
    ACTUATOR("ROLE_ACTUATOR");

    private String value;

    RolesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RolesEnum fromValue(String text) {
      for (RolesEnum b : RolesEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("roles")
  private List<RolesEnum> roles = null;

  /**
   * User State
   */
  public enum StateEnum {
    ACTIVE("ACTIVE"),
    
    DISABLED("DISABLED");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("state")
  private StateEnum state = null;

  @JsonProperty("username")
  private String username = null;

  public User account(BillingAccount account) {
    this.account = account;
    return this;
  }

   /**
   * Billing Account
   * @return account
  **/
  @ApiModelProperty(value = "Billing Account")
  public BillingAccount getAccount() {
    return account;
  }

  public void setAccount(BillingAccount account) {
    this.account = account;
  }

  public User id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * User ID in the system
   * @return id
  **/
  @ApiModelProperty(value = "User ID in the system")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public User org(DescribeOrganization org) {
    this.org = org;
    return this;
  }

   /**
   * Owning Organization
   * @return org
  **/
  @ApiModelProperty(value = "Owning Organization")
  public DescribeOrganization getOrg() {
    return org;
  }

  public void setOrg(DescribeOrganization org) {
    this.org = org;
  }

  public User profile(UserProfile profile) {
    this.profile = profile;
    return this;
  }

   /**
   * User Profile
   * @return profile
  **/
  @ApiModelProperty(value = "User Profile")
  public UserProfile getProfile() {
    return profile;
  }

  public void setProfile(UserProfile profile) {
    this.profile = profile;
  }

  public User registered(DateTime registered) {
    this.registered = registered;
    return this;
  }

   /**
   * Registration time
   * @return registered
  **/
  @ApiModelProperty(value = "Registration time")
  public DateTime getRegistered() {
    return registered;
  }

  public void setRegistered(DateTime registered) {
    this.registered = registered;
  }

  public User resourceLastModified(Long resourceLastModified) {
    this.resourceLastModified = resourceLastModified;
    return this;
  }

   /**
   * Timestamp of the last update of the user, organization or billing account
   * @return resourceLastModified
  **/
  @ApiModelProperty(value = "Timestamp of the last update of the user, organization or billing account")
  public Long getResourceLastModified() {
    return resourceLastModified;
  }

  public void setResourceLastModified(Long resourceLastModified) {
    this.resourceLastModified = resourceLastModified;
  }

  public User roles(List<RolesEnum> roles) {
    this.roles = roles;
    return this;
  }

  public User addRolesItem(RolesEnum rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<RolesEnum>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * User Roles
   * @return roles
  **/
  @ApiModelProperty(value = "User Roles")
  public List<RolesEnum> getRoles() {
    return roles;
  }

  public void setRoles(List<RolesEnum> roles) {
    this.roles = roles;
  }

  public User state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * User State
   * @return state
  **/
  @ApiModelProperty(value = "User State")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public User username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Username
   * @return username
  **/
  @ApiModelProperty(example = "jsmith@cool.io", value = "Username")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.account, user.account) &&
        Objects.equals(this.id, user.id) &&
        Objects.equals(this.org, user.org) &&
        Objects.equals(this.profile, user.profile) &&
        Objects.equals(this.registered, user.registered) &&
        Objects.equals(this.resourceLastModified, user.resourceLastModified) &&
        Objects.equals(this.roles, user.roles) &&
        Objects.equals(this.state, user.state) &&
        Objects.equals(this.username, user.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, id, org, profile, registered, resourceLastModified, roles, state, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    org: ").append(toIndentedString(org)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    registered: ").append(toIndentedString(registered)).append("\n");
    sb.append("    resourceLastModified: ").append(toIndentedString(resourceLastModified)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

